stages:
  - test
  - release

include:
  - project: 'muensmedia-docker/gitlab-ci-recipes'
    ref: master
    file: '/compression/.pack-zip-archive.yml'
  - project: 'muensmedia-docker/gitlab-ci-recipes'
    ref: master
    file: '/deployment/.rsync.yml'

"Create zip archive":
  extends: .pack-zip
  stage: test
  variables:
    ZIP_ARCHIVE_PATH: '../.release/'
    ZIP_ARCHIVE_NAME: er24_rechtstexte-${CI_COMMIT_TAG}
    ZIP_DESTINATION: ${ZIP_ARCHIVE_PATH}er24_rechtstexte-${CI_COMMIT_TAG}${ZIP_FILE_EXTENSION}
  before_script:
    - unlink .editorconfig
    - unlink .gitlab-ci.yml
  after_script:
    - mkdir .release
    - cp ${ZIP_DESTINATION} .release/
    - cp ${ZIP_DESTINATION} .release/er24_rechtstexte.zip
  artifacts:
    paths:
      - .release
  only:
    - tags

# upload new version to download server
deploy:rsync:
  extends: .deploy-rsync
  stage: release
  needs:
    - "Create zip archive"
  variables:
    PATH_TO_RSYNCIGNORE: ''
    FOLDER_TO_SYNC: '.release/'
    RSYNC_OPTIONS: ''
  before_script:
    - ls -la ${FOLDER_TO_SYNC}
  only:
    - tags

"Publish new version to TER":
  stage: release
  needs:
    - "Create zip archive"
  image: composer:2
  before_script:
    - composer global require typo3/tailor
  script:
    - >
      if [ -n "$CI_COMMIT_TAG" ] && [ -n "$TYPO3_API_TOKEN" ] && [ -n "$TYPO3_EXTENSION_KEY" ]; then
        echo -e "Preparing upload of release ${CI_COMMIT_TAG} to TER\n"
        # Upload
        TAG_MESSAGE=`git tag -n10 -l $CI_COMMIT_TAG | sed 's/^[0-9.]*[ ]*//g'`
        echo "Uploading release ${CI_COMMIT_TAG} to TER"
        /tmp/vendor/bin/tailor ter:publish --comment "$TAG_MESSAGE" --artefact=.release/er24_rechtstexte.zip "$CI_COMMIT_TAG" "$TYPO3_EXTENSION_KEY"
      fi;
  only:
    - tags

"Trigger tests for tags":
  stage: test
  trigger:
    project: erecht24/rechtstexte-plugin/typo3-rechtstexte-testing
    strategy: depend
  variables:
    COMPOSER_VERSION: $CI_COMMIT_REF_NAME
  only:
    - tags

"Trigger tests for branches":
  extends: "Trigger tests for tags"
  variables:
    COMPOSER_VERSION: dev-$CI_COMMIT_REF_NAME
  only:
    - branches
  except:
    - tags
