<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "er24_rechtstexte"
 *
 * Auto generated by Extension Builder 2020-12-08
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'eRecht24 Rechtstexte Extension',
    'description' => 'This extension allows the easy integration of imprint and privacy policy of eRecht24.',
    'category' => 'plugin',
    'author' => '',
    'author_email' => '',
    'state' => 'stable',
    'version' => '2.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '11.5.0-12.4.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
