<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "er24_rechtstexte"
 *
 * Auto generated by Extension Builder 2020-12-08
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'eRecht24 Rechtstexte Extension',
    'description' => 'This extension allows the easy integration of imprint and privacy policy of eRecht24.',
    'category' => 'plugin',
    'author' => '',
    'author_email' => '',
    'state' => 'stable',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.15',
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.0-11.5.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
